config/routes.rb
Rails.application.routes.draw do
  # resource :wechat, only: [:show, :create]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
      controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  get 'preview', to: 'pages#preview'
  get 'invitation_guest_list', to: 'pages#invitation_guest_list'
  get 'invitation_share_link', to: 'pages#invitation_share_link'
  get 'invitation_delete_link', to: 'pages#invitation_delete_link'
  resources :templates
  post 'invitations_choose_template', to: 'invitations#choose'
  resources :invitations do
    resources :guests
  end
  resources :invitations, path: '', as: 'custom_url_of_invitation', only: :show
end

app/views/templates/_form.html.erb
<div class="container">
  <%= simple_form_for(@template) do |f| %>
    <%= f.error_notification %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.input :title, placeholder: "Enter a title" %>
    <%= f.input :description, placeholder: "Enter an description" %>
    <%= f.input :stylesheet, collection: ["template_1","template_2"] %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.submit %>
  <% end %>
</div>

app/views/templates/index.html.erb
<h3>List of templates:</h3>

<% @templates.each do |template| %>
  <% if template.photo? %>
    <%= cl_image_tag template.photo.path, width: 200, height: 300, crop: :fill %>
  <% end %>
  <p><%= template.title %></p>
  <p><%= template.description %></p>
  <%= link_to "Preview", template_path(template) %>
  <%= link_to "Use", new_invitation_path(:template_id => template.id) %>
<% end %>

app/views/templates/show.html.erb
<h2> <%= @template.title %> </h2>
<p> <%= @template.description || 'something random' %> </p>
<p>stylesheet:</p>
<p> <%= @template.stylesheet %> </p>