config/routes.rb
Rails.application.routes.draw do
  # resource :wechat, only: [:show, :create]
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
      controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  get 'preview', to: 'pages#preview'
  get 'invitation_guest_list', to: 'pages#invitation_guest_list'
  get 'invitation_share_link', to: 'pages#invitation_share_link'
  get 'invitation_delete_link', to: 'pages#invitation_delete_link'
  resources :templates
  post 'invitations_choose_template', to: 'invitations#choose'
  resources :invitations do
    resources :guests
  end
  resources :invitations, path: '', as: 'custom_url_of_invitation', only: :show
end

app/views/pages/_delete_link.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <%= image_tag "illus-delete.svg" %>
      <h6 class="modal-title" id="myModalLabel">DELETE</h6>
    </div>
    <div class="modal-body">
      <h6>Are you sure you want to delete the story?</h6>
      <p>You won't be able to restore the deleted story</p>
      <%= link_to "DO IT!", invitation_path(id: invitation_delete_link.id), remote: true, method: :delete, class: "btn btn-steps" %>
  </div>
</div>

app/views/pages/_guest_list.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <%= image_tag "illus-guests.svg" %>
      <h6 class="modal-title" id="myModalLabel">GUESTS</h6>
    </div>
    <div class="modal-body" style="overflow: scroll">
      <table class="table table-striped">
        <tr>
          <th>Name</th>
          <th>Phone number</th>
          <th>Email</th>
          <th>Guests</th>
        </tr>
        <% invitation_guests.each do |guest| %>
          <tr>
            <td><%= guest.full_name %></td>
            <td><%= guest.phone_number %></td>
            <td><%= guest.email %></td>
            <td><%= guest.plus %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <p>Total: <%= invitation_guests.sum(:plus) %> RSVP</p>
  </div>
</div>

app/views/pages/_share_link.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <%= image_tag "illus-share.svg" %>
      <h6 class="modal-title" id="myModalLabel">SHARE</h6>
    </div>
    <div class="modal-body-share">
      <h6>URL</h6>
      <p id="share_url"><%= invitation_share_link %></p>
      <button class="btn btn-steps" id="share-button" data-clipboard-action="copy" data-clipboard-target="#share_url">Copy to clipboard</button>
      <br>
      <%= raw @svg %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container dashboard-container top-space">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <div id="profile-card" class="text-center">
        <% if current_user.facebook_picture_url %>
        <%= image_tag current_user.facebook_picture_url, class: "avatar-huge hidden-xs hidden-sm" %>
        <p><%= current_user.first_name %> <%= current_user.last_name %></p>
        <hr class="separator">
        <p><%= current_user.email %></p>
        <% else %>
        <%= image_tag "profile-big.svg", class: "avatar-huge hidden-xs hidden-sm" %>
        <p><%= current_user.first_name %> <%= current_user.last_name %></p>
        <hr class="separator">
        <p><%= current_user.email %><p>
          <% end %>
          <div id='profile-card-button'>
            <%= link_to t(".top_call_to_action", default: "Edit profile"), edit_user_registration_path, class: "btn btn-profile" %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-9">
        <div class="invitation-container">
          <h2 class="super-title">My invitations</h2>
          <div class="row">
            <div class="col-xs-12 col-md-6 col-lg-4">
              <div class="product pink-border">
                <%= link_to new_invitation_path do %>
                <%= image_tag "add.svg" %>
                <% end %>
              </div>
            </div>
            <% current_user.invitations.each do |invitation| %>
            <div class="col-xs-12 col-md-6 col-lg-4" id="invitation_<%= invitation.id -%>">
              <div class="product">
                <div class="image-wrapper">
                  <% if invitation.gallery? %>
                  <div class="product-image image" style="background-image: url('<%= cl_image_path invitation.gallery.first.path, gravity:"faces", crop:"fill" %>')">
                  </div>
                  <% else %>
                  <div class="image image-placeholder"></div>
                  <% end %>
                </div>

                <div class='product-body'>
                  <h3><%= invitation.story_title || "Welcome to our wedding!" %></h3>
                  <p>
                    <% if invitation.wedding_description != nil %>
                    <%= invitation.wedding_description.slice(0..23).concat('...') %>
                    <% else %>
                    We are getting married...
                    <% end %>
                  </p>
                </div>
                <div class="product-buttons-four text-center">
                  <%= link_to edit_invitation_path(invitation) do %>
                  <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                  <% end %>
                  <%= link_to preview_path(invitation_id: invitation.id) do %>
                  <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="Preview"></i>
                  <% end %>
                  <%= link_to invitation_share_link_path(invitation_id: invitation.id), remote: true do %>
                  <i class="fa fa-share" data-toggle="tooltip" data-placement="top" title="Share"></i>
                  <% end %>
                  <%= link_to invitation_delete_link_path(invitation_id: invitation.id), remote: true do %>
                  <i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="Delete"></i>
                  <% end %>
                </div>
                <div class="product-buttons-one text-center">
                  <% if invitation.rsvp? %>
                  <%= link_to invitation_guest_list_path(invitation_id: invitation.id), remote: true  do %>
                  <i class="fa fa-file-text" style="font-size: 14px" data-toggle="tooltip" data-placement="top" title="Guest List"></i>
                  <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="guestListModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>

  <div class="modal fade" id="invitationShareLink" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>

  <div class="modal fade" id="invitationDeleteLink" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  </div>

app/views/pages/home.html.erb
<div id="one"></div>
<div class="container text-center" id="logo">
  <%= image_tag "logo.svg" %>
  <p>BEST WEDDING INVITATION APP</p>
</div>

<div class="container text-center" id="laptop-phone">
  <%= image_tag "devices-desktop.png" %>
</div>

<div class="container text-center" id="features-container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-3">
      <div class="feature text-center">
        <div class="feature-img">
          <%= image_tag "inspire.svg" %>
        </div>
        <div class="feature-title">
          <h2>INSPIRE</h2>
        </div>
        <div class="feature-text">
          <p>Share your love story<br>with your lover,<br>or watch our demos<br>to get inspiration</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-3">
      <div class="feature text-center">
        <div class="feature-img">
          <%= image_tag "create.svg" %>
        </div>
        <div class="feature-title">
          <h2>CREATE</h2>
        </div>
        <div class="feature-text">
          <p>Easily add your<br>wedding details,<br> generate a unique<br>wedding invitation</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-3">
      <div class="feature text-center">
        <div class="feature-img">
          <%= image_tag "share.svg" %>
        </div>
        <div class="feature-title">
          <h2>SHARE</h2>
        </div>
        <div class="feature-text">
          <p>Share your lovestory<br>by different platforms<br>with all your<br>relatives and friends</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-3">
      <div class="feature text-center">
        <div class="feature-img">
          <%= image_tag "track.svg" %>
        </div>
        <div class="feature-title">
          <h2>TRACK</h2>
        </div>
        <div class="feature-text">
          <p>Simplify your<br>guest's RSVP,<br>and make it easy for you<br>to keep track of them</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <div class="wrapper text-center" id="templates">
  <h1>OUR TEMPLATES</h1>
  <div class="container">
    <div class="row">
      <%# @templates.each do |template| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="product">
            <div class="product-image">
              <%# if template.photo? %>
                <%#= cl_image_tag template.photo.path, width: 168, height: 138, crop:'fill' %>
              <%# else %>
                <%#= image_tag "img-placeholder.svg" %>
              <%# end %>
            </div>
            <div class='product-body'>
              <h3><%#= template.title %></h3>
              <p><%#= template.description.nil? ? "" : template.description.slice(0..20).concat('...') %></p>
            </div>
            <%#= link_to "", invitations_choose_template_path(id: template.id), class: "card-link", method: :post %>
          </div>
        </div>
      <%# end %>
    </div>
  </div>
</div> -->
<% @invitations = [{
  title: 'We are getting married!',
  description: 'What a nice day...',
  image: 'invitation1.jpg',
  url: 'http://wedtales.shanghaiwogeng.com/preview?invitation_id=3'
 }, {
  title: 'Welcome to our wedding!',
  description: 'We are getting married...',
  image: 'invitation2.jpg',
  url: 'http://wedtales.shanghaiwogeng.com/preview?invitation_id=11'
 }, {
  title: 'What a nice day!',
  description: 'Welcome to our wedding...',
  image: 'invitation3.jpg',
  url: 'http://wedtales.shanghaiwogeng.com/preview?invitation_id=13'
 }, {
  title: 'I love you!',
  description: 'Nice to meet you...',
  image: 'invitation4.jpg',
  url: 'http://wedtales.shanghaiwogeng.com/preview?invitation_id=12'
}] %>

<div class="wrapper text-center" id="templates">
  <h1>INVITATIONS</h1>
  <div class="row">
    <% @invitations.each do |invitation| %>
      <div class="col-md-6 col-lg-3">
        <div class="product">
          <div class="image-wrapper">
             <div class="image" style="background-image: url(<%= image_path invitation[:image] %>)"></div>
             <div class="caption">
               <h5><%=invitation[:title].capitalize %></h5>
               <p><%=invitation[:description] %></p>
              </div>
          </div>
          <%= link_to "", invitation[:url], class: "card-link", target: '_blank' %>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "START YOUR STORY", new_invitation_path, class: "btn btn-cta", id: "btn-create" %>
</div>

<div class="wrapper" id="map">
  <div class="container" id="contact-form">
    <h2>CONTACT</h2>
    <p><%= image_tag "fill-1.svg", class: "marker" %>  Naked Hub, 89 Taixing Road, Shanghai</p>
    <form class="form" style="margin-top: 50px;">
      <div class="form-group">
        <input class="form-control" type="text" name="name" placeholder="Your Name">
      </div>
      <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Your Email">
      </div>
      <div class="form-group">
        <textarea class="form-control" placeholder="Your Message"></textarea>
      </div>
      <div class="form-group">
        <button class="btn btn-cta">SEND</button>
      </div>
    </form>
  </div>
</div>

app/views/pages/invitation_delete_link.js.erb
$('#invitationDeleteLink').html("<%= j render partial: 'delete_link', locals: {invitation_delete_link: @invitation} -%>");
$('#invitationDeleteLink').modal('show');

app/views/pages/invitation_guest_list.js.erb
$('#guestListModel').html("<%= j render partial: 'guest_list', locals: {invitation_guests: @guests} -%>");
$('#guestListModel').modal('show');

app/views/pages/invitation_share_link.js.erb
$('#invitationShareLink').html("<%= j render partial: 'share_link', locals: {invitation_share_link: @share_link} -%>");
$('#invitationShareLink').modal('show');

var clipboard = new Clipboard('#share-button');
  console.log(clipboard);

app/views/pages/preview.html.erb
<div class="wrapper">
  <div class="preview-container">
    <div class="preview-qr-container">
      <h1>QR CODE</h1>
      <%= raw @svg %>
      <%= link_to "Go Back", dashboard_path, class: "btn btn-devise btn-steps" %>
    </div>
    <div class="iphone-container">
      <div id="preview-iphone">
        <div id="preview-iphone-screen">
        <iframe src="<%= @invitation_url %>" id="preview-iphone-display" style= "border: 0"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<%#= invitation_share_link %>